name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World!"

      - name: Print current date
        run: date

      - name: List directory contents
        run: ls -l
